# configurcaoa porta do servidor tomcat
server:
  port: 8080
  servlet:
    context-path: /bootcamp

# configuracao da base de dados postgress
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none 

# Desricao para a API
application:
  description: Projeto criado para o bootcamp DIO - Santander
    
    
    
    

  
